"""Change varchar

Revision ID: 5d5175e7d1dd
Revises: 739d3033f509
Create Date: 2023-10-20 10:38:11.954748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d5175e7d1dd'
down_revision = '739d3033f509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
